apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: pre-sales
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30007
  selector:
    app: hello-world

