name: 'Deploy to GKE'



on:
  workflow_dispatch:

jobs:
  setup-gke:
    name: 'Set Up GCP Infrastructure'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: 'Set up Terraform'
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > google-credentials.json
        cat google-credentials.json  # Optional: for debugging to check if file is correct
        terraform init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: google-credentials.json

    - name: 'Terraform Plan'
      run: terraform plan

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve

  deploy-to-gke:
    needs: setup-gke
    name: 'Deploy Application'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: 'List Authenticated Accounts'
      run: gcloud auth list

        
    - name: 'Set up Terraform'
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > google-credentials.json
        gcloud auth activate-service-account --key-file=google-credentials.json
        terraform init
    

    - name: 'Get GKE credentials'
      run: |
        gcloud container clusters get-credentials auto-private-cluster --region asia-south1 --project ${{ secrets.GCP_PROJECT }}

    - name: 'Deploy to GKE'
      run: |
        kubectl apply -f hello-world-deployment.yaml
        kubectl apply -f hello-world-service.yaml

