name: 'Deploy to GKE'

on:
  push:
    branches:
      - main

jobs:
  setup-gke:
    name: 'Set Up GCP Infrastructure'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: 'Terraform Init'
      run: |
        terraform init
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: 'Terraform Plan'
      run: |
        terraform plan
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: 'Terraform Apply'
      run: |
        terraform apply -auto-approve
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  deploy-to-gke:
    needs: [setup-gke]
    name: 'Deploy Application'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: 'Get GKE credentials'
      run: |
        gcloud container clusters get-credentials auto-pilot-cluster --region asia-south1 --project ${{ env.GCP_PROJECT }}
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: 'Deploy to GKE'
      run: |
        kubectl apply -f hello-world-deployment.yaml
        kubectl apply -f hello-world-service.yaml
