name: 'Destroy GKE Infrastructure'

on: 
  workflow_dispatch:

jobs:
  destroy-gke:
    name: 'Destroy Infrastructure'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@main

    - name: 'Prepare Google Credentials'
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > google-credentials.json
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: 'Terraform Init'
      run: terraform init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: google-credentials.json
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

    - name: 'Terraform Destroy'
      run: terraform destroy -auto-approve
      env:
        GOOGLE_APPLICATION_CREDENTIALS: google-credentials.json
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
