name: 'Destroy GKE Infrastructure'

on: 
  workflow_dispatch:

jobs:
  destroy-gke:
    name: 'Destroy Infrastructure'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@master

    - name: 'Terraform Init'
      run: |
        terraform init
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: 'Terraform Destroy'
      run: |
        terraform destroy -auto-approve
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
